=== dovvla/vaccination-app/xml/potvrda_o_vakcinaciji.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://tim.robot/potvrda_o_vakcinaciji"
    xmlns:pov="http://tim.robot/potvrda_o_vakcinaciji">
    <xs:element name="Potvrda">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Sifra_potvrde" type="xs:string"/>
                <xs:element name="Podaci_pacijenta">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Ime" type="xs:string"/>
                            <xs:element name="Prezime" type="xs:string"/>
                            <xs:element name="Pol">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Musko"/>
                                        <xs:enumeration value="Zensko"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="JMBG">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="\d{13}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element maxOccurs="2" type="pov:TDoza_vakcine" name="Doza_vakcine"/>
                <xs:element name="Zdravstvena_ustanova" type="xs:string"/>
                <xs:element name="Naziv_vakcine">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="Pfizer"/>
                            <xs:enumeration value="Sputnik"/>
                            <xs:enumeration value="Sinopharm"/>
                            <xs:enumeration value="AZ"/>
                            <xs:enumeration value="Moderna"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Datum" type="xs:date"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="TDoza_vakcine">
        <xs:sequence>
            <xs:element name="Datum_davanja" type="xs:date"/>
            <xs:element name="Serija" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== dovvla/vaccination-app/xml/potvrda_o_vakcinaciji1.xml
<?xml version="1.0" encoding="UTF-8"?>
<Potvrda xmlns="http://tim.robot/potvrda_o_vakcinaciji"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://tim.robot/potvrda_o_vakcinaciji potvrda_o_vakcinaciji.xsd">
    <Sifra_potvrde>ecc3e162-2346-45c6-859d-df658f48bca6</Sifra_potvrde>
    <Podaci_pacijenta>
        <Ime>Nikola</Ime>
        <Prezime>Nikolic</Prezime>
        <Pol>Musko</Pol>
        <JMBG>0303995666666</JMBG>
    </Podaci_pacijenta>
    <Doza_vakcine>
        <Datum_davanja>2021-05-04</Datum_davanja>
        <Serija>EN1193</Serija>
    </Doza_vakcine>
    <Doza_vakcine>
        <Datum_davanja>2021-05-25</Datum_davanja>
        <Serija>EN1193</Serija>
    </Doza_vakcine>
    <Zdravstvena_ustanova>Vakcinski punkt Novi Sad</Zdravstvena_ustanova>
    <Naziv_vakcine>Pfizer</Naziv_vakcine>
    <Datum>2021-05-25</Datum>
</Potvrda>

=== dovvla/vaccination-app/vaccapp/src/main/resources/xml/potvrda_o_vakcinaciji1.xml
<?xml version="1.0" encoding="UTF-8"?>
<Potvrda xmlns="http://tim.robot/potvrda_o_vakcinaciji"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://tim.robot/potvrda_o_vakcinaciji potvrda_o_vakcinaciji.xsd"
         xmlns:pred="http://tim.robot/rdf/predicate/"
 about="http://tim.robot/potvrda_o_vakcinaciji/potvrda_o_vakcinaciji1">
    <Sifra_potvrde>ecc3e162-2346-45c6-859d-df658f48bca6</Sifra_potvrde>
    <QRkod>nesto</QRkod>
    <Podaci_pacijenta>
        <Ime>Nikola</Ime>
        <Prezime>Nikolic</Prezime>
        <Pol>Musko</Pol>
        <JMBG>0303995666666</JMBG>
    </Podaci_pacijenta>
    <Doza_vakcine>
        <Datum_davanja>2021-05-04</Datum_davanja>
        <Serija>EN1193</Serija>
    </Doza_vakcine>
    <Doza_vakcine>
        <Datum_davanja>2021-05-25</Datum_davanja>
        <Serija>EN1193</Serija>
    </Doza_vakcine>
    <Zdravstvena_ustanova datatype="xs:string" property="pred:zdravstvena_ustanova">Vakcinski punkt Novi Sad</Zdravstvena_ustanova>
    <Naziv_vakcine>Pfizer</Naziv_vakcine>
    <Datum property="pred:datum" datatype="xs:date">2021-05-25</Datum>
</Potvrda>
