=== dovvla/vaccination-app/xml/zahtev_za_sertifikat.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://tim.robot/zahtev_za_sertifikat"
    xmlns:zzs="http://tim.robot/zahtev_za_sertifikat">

    <xs:element name="Zahtev">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ID" type="xs:positiveInteger"/>
                <xs:element name="Podaci_o_podnosiocu">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Ime" type="xs:string"/>
                            <xs:element name="Prezime" type="xs:string"/>
                            <xs:element name="Datum_rodjenja" type="xs:date"/>
                            <xs:element name="Pol">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Musko"/>
                                        <xs:enumeration value="Zensko"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="JMBG">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="\d{13}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Broj_pasosa">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="\d{9}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Razlog_za_podnosenje" type="xs:string"/>
                <xs:element name="Mesto" type="xs:string"/>
                <xs:element name="Datum" type="xs:date"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== dovvla/vaccination-app/xml/zahtev_za_sertifikat1.xml
<?xml version="1.0" encoding="UTF-8"?>
<Zahtev xmlns="http://tim.robot/zahtev_za_sertifikat"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://tim.robot/zahtev_za_sertifikat zahtev_za_sertifikat.xsd">
    <Podaci_o_podnosiocu>
        <Ime>Nikola</Ime>
        <Prezime>Nikolic</Prezime>
        <Datum_rodjenja>1995-05-04</Datum_rodjenja>
        <Pol>Musko</Pol>
        <JMBG>0405995666666</JMBG>
        <Broj_pasosa>012345678</Broj_pasosa>
    </Podaci_o_podnosiocu>
    <Razlog_za_podnosenje>Putovanje</Razlog_za_podnosenje>
    <Mesto>Novi Sad</Mesto>
    <Datum>2021-05-04</Datum>
</Zahtev>
