=== dovvla/vaccination-app/vaccapp/src/main/resources/xsd/iskazivanje_interesovanja_za_vakcinaciju.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://tim.robot/iskazivanje_interesovanja_za_vakcinaciju"
    xmlns:iizv="http://tim.robot/iskazivanje_interesovanja_za_vakcinaciju">

    <xs:element name="Obrazac_interesovanja">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Licni_podaci">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Drzavljanstvo">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="RS"/>
                                        <xs:enumeration value="Strani sa boravkom"/>
                                        <xs:enumeration value="Strani bez boravka"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="JMBG">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="\d{13}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Ime" type="xs:string"/>
                            <xs:element name="Prezime" type="xs:string"/>
                            <xs:element name="Imejl">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern
                                            value="[A-Z0-9a-z._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,64}"
                                        />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Broj_mobilnog_telefona">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="06\d{7,8}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Broj_fiksnog_telefona">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="0\d{8,9}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Zeljena_lokacija_vakcinacije" type="xs:string"/>
                <xs:element name="Zeljena_vakcina">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="Pfizer"/>
                            <xs:enumeration value="Sputnik"/>
                            <xs:enumeration value="Sinopharm"/>
                            <xs:enumeration value="AZ"/>
                            <xs:enumeration value="Moderna"/>
                            <xs:enumeration value="Bilo koja"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Davalac_krvi">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:whiteSpace value="preserve"/>
                            <xs:enumeration value="Da"/>
                            <xs:enumeration value="Ne"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Datum" type="xs:date"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== dovvla/vaccination-app/xml/iskazivanje_interesovanja_za_vakcinaciju_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<Obrazac_interesovanja xmlns="http://tim.robot/iskazivanje_interesovanja_za_vakcinaciju"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://tim.robot/iskazivanje_interesovanja_za_vakcinaciju iskazivanje_interesovanja_za_vakcinaciju.xsd">
    <ID>123456789</ID>
    <Licni_podaci>
        <Drzavljanstvo>RS</Drzavljanstvo>
        <JMBG>0303999800092</JMBG>
        <Ime>Nikola</Ime>
        <Prezime>Nikolic</Prezime>
        <Imejl>nikola.nikolic@gmail.com</Imejl>
        <Broj_mobilnog_telefona>069696969</Broj_mobilnog_telefona>
        <Broj_fiksnog_telefona>0111234567</Broj_fiksnog_telefona>
    </Licni_podaci>
    <Zeljena_lokacija_vakcinacije>Vakcinski punkt Novi Sad</Zeljena_lokacija_vakcinacije>
    <Zeljena_vakcina>Pfizer</Zeljena_vakcina>
    <Davalac_krvi>Ne</Davalac_krvi>
    <Datum>2021-05-04</Datum>
</Obrazac_interesovanja>
