=== dovvla/vaccination-app/vaccapp/src/main/resources/xsd/izvestaj_o_imunizaciji.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://tim.robot/izvestaj_o_imunizaciji"
    xmlns:ioi="http://tim.robot/izvestaj_o_imunizaciji">

    <xs:element name="Izvestaj">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Period_izvestaja">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Datum_od" type="xs:date"/>
                            <xs:element name="Datum_do" type="xs:date"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Podnetih_interesovanja_imunizacije" type="xs:positiveInteger"/>
                <xs:element name="Zahtevi_za_zeleni_sertifikat" type="xs:positiveInteger"/>
                <xs:element name="Izdatih_zelenih_sertifikata" type="xs:positiveInteger"/>
                <xs:element name="Podaci_o_datim_dozama">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Ukupno_doza" type="xs:positiveInteger"/>
                            <xs:element name="Broj_date_prve_doze" type="xs:positiveInteger"/>
                            <xs:element name="Broj_date_druge_doze" type="xs:positiveInteger"/>
                            <xs:element name="Broj_date_trece_doze" type="xs:positiveInteger"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Raspodela_po_proizvodjacima">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Broj_pfizer_vakcina" type="xs:positiveInteger"/>
                            <xs:element name="Broj_sinopharm_vakcina" type="xs:positiveInteger"/>
                            <xs:element name="Broj_sputnik_vakcina" type="xs:positiveInteger"/>
                            <xs:element name="Broj_az_vakcina" type="xs:positiveInteger"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Datum" type="xs:date"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== dovvla/vaccination-app/vaccapp/src/main/resources/xml/izvestaj_o_imunizaciji_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<Izvestaj xmlns="http://tim.robot/izvestaj_o_imunizaciji"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://tim.robot/izvestaj_o_imunizaciji izvestaj_o_imunizaciji.xsd">
    <Period_izvestaja>
        <Datum_od>2021-08-04</Datum_od>
        <Datum_do>2021-09-04</Datum_do>
    </Period_izvestaja>
    <Podnetih_interesovanja_imunizacije>1000</Podnetih_interesovanja_imunizacije>
    <Zahtevi_za_zeleni_sertifikat>50</Zahtevi_za_zeleni_sertifikat>
    <Izdatih_zelenih_sertifikata>50</Izdatih_zelenih_sertifikata>
    <Podaci_o_datim_dozama>
        <Ukupno_doza>150</Ukupno_doza>
        <Broj_date_prve_doze>50</Broj_date_prve_doze>
        <Broj_date_druge_doze>50</Broj_date_druge_doze>
        <Broj_date_trece_doze>50</Broj_date_trece_doze>
    </Podaci_o_datim_dozama>
    <Raspodela_po_proizvodjacima>
        <Broj_pfizer_vakcina>20</Broj_pfizer_vakcina>
        <Broj_sinopharm_vakcina>100</Broj_sinopharm_vakcina>
        <Broj_sputnik_vakcina>20</Broj_sputnik_vakcina>
        <Broj_az_vakcina>10</Broj_az_vakcina>
    </Raspodela_po_proizvodjacima>
    <Datum>2021-09-05</Datum>
</Izvestaj>
