=== dovvla/vaccination-app/vaccapp/src/main/resources/xsd/saglasnost.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://tim.robot/obrazac_saglasnosti_za_imunizaciju"
    xmlns:oszi="http://tim.robot/obrazac_saglasnosti_za_imunizaciju" xmlns:pred="http://tim.robot/rdf/predicate/">

    <xs:element name="Obrazac">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Podaci_o_pacijentu">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Drzavljanstvo">
                                <xs:complexType>
                                    <xs:choice>
                                        <xs:element name="JMBG">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                  <xs:pattern value="\d{13}"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="Strano_drzavljanstvo">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="Naziv" type="xs:string"/>
                                                  <xs:element name="Br_pasosa">
                                                  <xs:simpleType>
                                                  <xs:restriction base="xs:string">
                                                  <xs:pattern value="\d{9}"/>
                                                  </xs:restriction>
                                                  </xs:simpleType>
                                                  </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:choice>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Prezime" type="oszi:TPrezime"/>
                            <xs:element name="Ime" type="oszi:TIme"/>
                            <xs:element name="Ime_roditelja" type="xs:string"/>
                            <xs:element name="Pol">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Muski"/>
                                        <xs:enumeration value="Zenski"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Datum_rodjenja" type="xs:date"/>
                            <xs:element name="Mesto_rodjenja" type="xs:string"/>
                            <xs:element type="oszi:TAdresa" name="Adresa"/>
                            <xs:element name="Naselje" type="xs:string"/>
                            <xs:element name="Grad" type="xs:string"/>
                            <xs:element name="Telefon_fiksni">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="0\d{8,9}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Telefon_mobilni">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="06\d{7,8}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Imejl">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern
                                            value="[A-Z0-9a-z._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,64}"
                                        />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Radni_status">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Zaposlen"/>
                                        <xs:enumeration value="Nezaposlen"/>
                                        <xs:enumeration value="Penzioner"/>
                                        <xs:enumeration value="Ucenik"/>
                                        <xs:enumeration value="Student"/>
                                        <xs:enumeration value="Dete"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Zanimanje_zaposlenog">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Zdravstvena zastita"/>
                                        <xs:enumeration value="Socijalna zastita"/>
                                        <xs:enumeration value="Prosveta"/>
                                        <xs:enumeration value="MUP"/>
                                        <xs:enumeration value="Vojska RS"/>
                                        <xs:enumeration value="Drugo"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Korisnik_socijalne_zastite">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="DA"/>
                                        <xs:enumeration value="NE"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Sediste_socijalne_zastite" nillable="true"
                                minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Naziv" type="xs:string" nillable="true"/>
                                        <xs:element name="Opstina" type="xs:string" nillable="true"
                                        />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Podaci_o_saglasnosti">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Saglasnost">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="SAGLASAN SAM"/>
                                        <xs:enumeration value="NISAM SAGLASAN"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Naziv_imunoloskog_leka" type="xs:string"/>
                            <xs:element name="Datum" type="oszi:TDatumIzdavanja"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Evidencija_o_vakcinaciji" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Zdravstvena_ustanova" type="xs:string"/>
                            <xs:element name="Vakcinacijski_punkt" type="xs:string"/>
                            <xs:element name="Podaci_o_lekaru">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Ime" type="xs:string"/>
                                        <xs:element name="Prezime" type="xs:string"/>
                                        <xs:element name="Faksimil" type="xs:string"/>
                                        <xs:element name="Broj_telefona">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                  <xs:pattern value="06\d{7,8}"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Podaci_o_izvrsenim_imunizacijama">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element maxOccurs="2" minOccurs="1"
                                            type="oszi:TPrimljena_vakcina" name="Primljena_vakcina"/>
                                        <xs:element name="Privremene_kontraindikacije" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="Datum" type="xs:date"/>
                                                  <xs:element name="Dijagnoza" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="Odluka_komisije" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="about" type="xs:string" use="required"/>
            <xs:attribute name="href" type="xs:string" use="required"/>
            <xs:attribute fixed="pred:fromObrazacInteresovanja" name="rel" type="xs:string" use="required" />
        </xs:complexType>
    </xs:element>

    <xs:complexType name="TAdresa">
        <xs:sequence>
            <xs:element name="Ulica" type="xs:string"/>
            <xs:element name="Broj" type="xs:positiveInteger"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="TPrimljena_vakcina">
        <xs:sequence maxOccurs="1" minOccurs="1">
            <xs:element name="Naziv" type="oszi:TNazivVakcine"/>
            <xs:element name="Datum_izdavanja" type="xs:date"/>
            <xs:element name="Ekstremitet">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="DR"/>
                        <xs:enumeration value="LR"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Serija_vakcine" type="xs:string"/>
            <xs:element name="Proizvodjac" type="xs:string"/>
            <xs:element name="Nezeljena_reakcija" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="TIme">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="property" use="required" fixed="pred:ime"/>
                <xs:attribute name="datatype" use="required" fixed="xs:string"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="TPrezime">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="property" use="required" fixed="pred:prezime"/>
                <xs:attribute name="datatype" use="required" fixed="xs:string"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="TNazivVakcine">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="property" use="required" fixed="pred:naziv_vakcine"/>
                <xs:attribute name="datatype" use="required" fixed="xs:string"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="TDatumIzdavanja">
        <xs:simpleContent>
            <xs:extension base="xs:date">
                <xs:attribute name="property" use="required" fixed="pred:datum"/>
                <xs:attribute name="datatype" use="required" fixed="xs:date"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

</xs:schema>

=== dovvla/vaccination-app/vaccapp/src/main/resources/xml/saglasnost1.xml
<?xml version="1.0" encoding="UTF-8"?>
<Obrazac xmlns="http://tim.robot/obrazac_saglasnosti_za_imunizaciju"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://tim.robot/obrazac_saglasnosti_za_imunizaciju saglasnost.xsd" about="http://tim.robot/obrazac_saglasnosti_za_imunizaciju/saglasnost1"
 rel="pred:fromObrazacInteresovanja" href="http://tim.robot/iskazivanje_interesovanja_za_vakcinaciju/iskazivanje_interesovanja_za_vakcinaciju_1"
 xmlns:pred="http://tim.robot/rdf/predicate/">
    <Podaci_o_pacijentu>
        <Drzavljanstvo>
            <JMBG>0505000111111</JMBG>
        </Drzavljanstvo>
        <Prezime property="pred:prezime" datatype="xs:string">Hrvotic</Prezime>
        <Ime property="pred:ime" datatype="xs:string">Srba</Ime>
        <Ime_roditelja>Gojko</Ime_roditelja>
        <Pol>Muski</Pol>
        <Datum_rodjenja>2000-05-04</Datum_rodjenja>
        <Mesto_rodjenja>Becej</Mesto_rodjenja>
        <Adresa>
            <Ulica>Splitska</Ulica>
            <Broj>50</Broj>
        </Adresa>
        <Naselje>Becej</Naselje>
        <Grad>Becej</Grad>
        <Telefon_fiksni>011696969</Telefon_fiksni>
        <Telefon_mobilni>069420420</Telefon_mobilni>
        <Imejl>srbo@mail.rs</Imejl>
        <Radni_status>Zaposlen</Radni_status>
        <Zanimanje_zaposlenog>Zdravstvena zastita</Zanimanje_zaposlenog>
        <Korisnik_socijalne_zastite>NE</Korisnik_socijalne_zastite>
    </Podaci_o_pacijentu>
    <Podaci_o_saglasnosti>
        <Saglasnost>SAGLASAN SAM</Saglasnost>
        <Naziv_imunoloskog_leka>SARS-CoV-2 Vakcinaciono sredstvo za imunizaciju ljudskog organizma, tzv. Pfizer</Naziv_imunoloskog_leka>
        <Datum property="pred:datum" datatype="xs:date">2021-05-04</Datum>
    </Podaci_o_saglasnosti>
    <Evidencija_o_vakcinaciji>
        <Zdravstvena_ustanova>Vakcinski punkt Novi Sad</Zdravstvena_ustanova>
        <Vakcinacijski_punkt>Punkt 1</Vakcinacijski_punkt>
        <Podaci_o_lekaru>
            <Ime>Edita</Ime>
            <Prezime>Stokic</Prezime>
            <Faksimil>vafer12345</Faksimil>
            <Broj_telefona>069666666</Broj_telefona>
        </Podaci_o_lekaru>
        <Podaci_o_izvrsenim_imunizacijama>
            <Primljena_vakcina>
                <Naziv property="pred:naziv_vakcine" datatype="xs:string">Pfizer</Naziv>
                <Datum_izdavanja>2021-05-04</Datum_izdavanja>
                <Ekstremitet>DR</Ekstremitet>
                <Serija_vakcine>EN1193</Serija_vakcine>
                <Proizvodjac>Pfizer-BioNTech</Proizvodjac>
                <Nezeljena_reakcija>Glavobolja, reuma</Nezeljena_reakcija>
            </Primljena_vakcina>
            <Primljena_vakcina>
                <Naziv property="pred:naziv_vakcine" datatype="xs:string">Pfizer</Naziv>
                <Datum_izdavanja>2021-05-25</Datum_izdavanja>
                <Ekstremitet>DR</Ekstremitet>
                <Serija_vakcine>EN1193</Serija_vakcine>
                <Proizvodjac>Pfizer-BioNTech</Proizvodjac>
                <Nezeljena_reakcija>Bol u ruci</Nezeljena_reakcija>
            </Primljena_vakcina>
            <Odluka_komisije>Pacijent nek odmara, pije topli caj i oblaci se slojevito.</Odluka_komisije>
        </Podaci_o_izvrsenim_imunizacijama>
    </Evidencija_o_vakcinaciji>
</Obrazac>

=== dovvla/vaccination-app/xml/saglasnost1.xml
<?xml version="1.0" encoding="UTF-8"?>
<Obrazac xmlns="http://tim.robot/obrazac_saglasnosti_za_imunizaciju"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://tim.robot/obrazac_saglasnosti_za_imunizaciju saglasnost.xsd">
    <Podaci_o_pacijentu>
        <Drzavljanstvo>
            <JMBG>0505000111111</JMBG>
        </Drzavljanstvo>
        <Prezime>Hrvotic</Prezime>
        <Ime>Srba</Ime>
        <Ime_roditelja>Gojko</Ime_roditelja>
        <Pol>Muski</Pol>
        <Datum_rodjenja>2000-05-04</Datum_rodjenja>
        <Mesto_rodjenja>Becej</Mesto_rodjenja>
        <Adresa>
            <Ulica>Splitska</Ulica>
            <Broj>50</Broj>
        </Adresa>
        <Naselje>Becej</Naselje>
        <Grad>Becej</Grad>
        <Telefon_fiksni>011696969</Telefon_fiksni>
        <Telefon_mobilni>069420420</Telefon_mobilni>
        <Imejl>srbo@mail.rs</Imejl>
        <Radni_status>Zaposlen</Radni_status>
        <Zanimanje_zaposlenog>Zdravstvena zastita</Zanimanje_zaposlenog>
        <Korisnik_socijalne_zastite>NE</Korisnik_socijalne_zastite>
        <Sediste_socijalne_zastite>
            <Naziv></Naziv>
            <Opstina></Opstina>
        </Sediste_socijalne_zastite>
    </Podaci_o_pacijentu>
    <Podaci_o_saglasnosti>
        <Saglasnost>SAGLASAN SAM</Saglasnost>
        <Naziv_imunoloskog_leka>SARS-CoV-2 Vakcinaciono sredstvo za imunizaciju ljudskog organizma, tzv. Pfizer</Naziv_imunoloskog_leka>
        <Datum>2021-05-04</Datum>
    </Podaci_o_saglasnosti>
    <Evidencija_o_vakcinaciji>
        <Zdravstvena_ustanova>Vakcinski punkt Novi Sad</Zdravstvena_ustanova>
        <Vakcinacijski_punkt>Punkt 1</Vakcinacijski_punkt>
        <Podaci_o_lekaru>
            <Ime>Edita</Ime>
            <Prezime>Stokic</Prezime>
            <Faksimil>vafer12345</Faksimil>
            <Broj_telefona>069666666</Broj_telefona>
        </Podaci_o_lekaru>
        <Podaci_o_izvrsenim_imunizacijama>
            <Primljena_vakcina>
                <Naziv>Pfizer</Naziv>
                <Datum_izdavanja>2021-05-04</Datum_izdavanja>
                <Ekstremitet>DR</Ekstremitet>
                <Serija_vakcine>EN1193</Serija_vakcine>
                <Proizvodjac>Pfizer-BioNTech</Proizvodjac>
                <Nezeljena_reakcija>Glavobolja, reuma</Nezeljena_reakcija>
            </Primljena_vakcina>
            <Primljena_vakcina>
                <Naziv>Pfizer</Naziv>
                <Datum_izdavanja>2021-05-25</Datum_izdavanja>
                <Ekstremitet>DR</Ekstremitet>
                <Serija_vakcine>EN1193</Serija_vakcine>
                <Proizvodjac>Pfizer-BioNTech</Proizvodjac>
                <Nezeljena_reakcija>Bol u ruci</Nezeljena_reakcija>
            </Primljena_vakcina>
            <Odluka_komisije>Pacijent nek odmara, pije topli caj i oblaci se slojevito.</Odluka_komisije>
        </Podaci_o_izvrsenim_imunizacijama>
    </Evidencija_o_vakcinaciji>
</Obrazac>
