=== dovvla/vaccination-app/vaccapp/src/main/resources/xsd/zeleni_sertifikat.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://tim.robot/zeleni_sertifikat"
    xmlns:zs="http://tim.robot/zeleni_sertifikat">

    <xs:element name="Sertifikat">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Podaci_o_sertifikatu">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Broj" type="xs:positiveInteger"/>
                            <xs:element name="Datum_i_vreme" type="xs:dateTime"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Podaci_o_pacijentu">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Ime" type="xs:string"/>
                            <xs:element name="Prezime" type="xs:string"/>
                            <xs:element name="Pol">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Musko"/>
                                        <xs:enumeration value="Zensko"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Datum_rodjenja" type="xs:date"/>
                            <xs:element name="JMBG">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="\d{13}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Broj_pasosa">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="\d{9}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element maxOccurs="2" minOccurs="0" type="zs:TDoza_vakcinacije" name="Doza_vakcinacije"/>
                <xs:element maxOccurs="unbounded" minOccurs="0" type="zs:TKovid_test" name="Kovid_test"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

        <xs:complexType name="TDoza_vakcinacije">
            <xs:sequence>
                <xs:element name="Tip" type="xs:string"/>
                <xs:element name="Proizvodjac" type="xs:string"/>
                <xs:element name="Serija" type="xs:string"/>
                <xs:element name="Datum" type="xs:date"/>
                <xs:element name="Zdravstvena_ustanova" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    
        <xs:complexType name="TKovid_test">
            <xs:sequence>
                <xs:element name="Naziv_testa">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="PCR"/>
                            <xs:enumeration value="Antigen"/>
                            <xs:enumeration value="IgG"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Vrsta_uzorka" type="xs:string"/>
                <xs:element name="Proizvodjac_testa" type="xs:string"/>
                <xs:element name="Datum_i_vreme_uzorkovanja" type="xs:dateTime"/>
                <xs:element name="Rezultat">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="Pozitivan"/>
                            <xs:enumeration value="Negativan"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Laboratorija" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
   
</xs:schema>

=== dovvla/vaccination-app/vaccapp/src/main/resources/xml/zeleni_sertifikat1.xml
<?xml version="1.0" encoding="UTF-8"?>
<Sertifikat xmlns="http://tim.robot/zeleni_sertifikat"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://tim.robot/zeleni_sertifikat zeleni_sertifikat.xsd">
    <Podaci_o_sertifikatu>
        <Broj>12345</Broj>
        <Datum_i_vreme>2021-05-26T18:13:51.0</Datum_i_vreme>
        <QRkod>www.exampleqr.com</QRkod>
    </Podaci_o_sertifikatu>
    <Podaci_o_pacijentu>
        <Ime>Nikola</Ime>
        <Prezime>Nikolic</Prezime>
        <Pol>Musko</Pol>
        <Datum_rodjenja>1995-05-04</Datum_rodjenja>
        <JMBG>0405995666666</JMBG>
        <Broj_pasosa>123456789</Broj_pasosa>
    </Podaci_o_pacijentu>
    <Doza_vakcinacije>
        <Tip>Pfizer</Tip>
        <Proizvodjac>Pfizer-BioNTech</Proizvodjac>
        <Serija>EN1193</Serija>
        <Datum>2021-05-04</Datum>
        <Zdravstvena_ustanova>Vakcinski punkt Novi Sad</Zdravstvena_ustanova>
    </Doza_vakcinacije>
    <Doza_vakcinacije>
        <Tip>Pfizer</Tip>
        <Proizvodjac>Pfizer-BioNTech</Proizvodjac>
        <Serija>EN1193</Serija>
        <Datum>2021-05-25</Datum>
        <Zdravstvena_ustanova>Vakcinski punkt Novi Sad</Zdravstvena_ustanova>
    </Doza_vakcinacije>
    <Kovid_test>
        <Naziv_testa>PCR</Naziv_testa>
        <Vrsta_uzorka>Nazalni bris</Vrsta_uzorka>
        <Proizvodjac_testa>Batut</Proizvodjac_testa>
        <Datum_i_vreme_uzorkovanja>2021-05-26T18:13:51.0</Datum_i_vreme_uzorkovanja>
        <Rezultat>Negativan</Rezultat>
        <Laboratorija>Novi Sad 1</Laboratorija>
    </Kovid_test>
    <Kovid_test>
        <Naziv_testa>Antigen</Naziv_testa>
        <Vrsta_uzorka>Nazalni bris</Vrsta_uzorka>
        <Proizvodjac_testa>Batut</Proizvodjac_testa>
        <Datum_i_vreme_uzorkovanja>2021-05-25T18:13:51.0</Datum_i_vreme_uzorkovanja>
        <Rezultat>Negativan</Rezultat>
        <Laboratorija>Novi Sad 2</Laboratorija>
    </Kovid_test>
</Sertifikat>
